#!/usr/bin/env python3
"""Generate the contract-oriented fasmg Win32 projection."""

from __future__ import annotations

import argparse
import json
import shutil
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from win32json_fasm2 import (
    Fasm2Writer,
    Win32JsonModel,
    api_prefix,
    fasm_string,
    fasm_value,
    is_apiset_dll,
    is_rename,
    sanitize_identifier,
)


GENERATED_MARKER = "; Generated by scripts/win32json_fasm2_calm.py. DO NOT EDIT."
RUNTIME_NAMES = {"interface", "fastcall", "bits32", "bits64"}
SEMANTIC_PARAM_RESOLVERS = {
    ("KERNEL32.dll", "ExitProcess", "uExitCode"): "win32.WIN32_ERROR",
}


@dataclass
class FunctionContract:
    index: int
    item: dict[str, Any]
    set_name: str
    dll_alias: str
    source_name: str
    contract_name: str
    target_id: str
    canonical: str
    public: bool = False
    public_reason: str = ""


def safe_component(text: str) -> str:
    value = sanitize_identifier(text)
    if is_rename(value):
        value += "_"
    return value


def type_text(expr: dict[str, Any]) -> str:
    kind = expr.get("Kind")
    if kind == "Native":
        return str(expr.get("Name", "?"))
    if kind == "ApiRef":
        return str(expr.get("Name", "?"))
    if kind == "PointerTo":
        return type_text(expr.get("Child") or {}) + "*"
    if kind == "LPArray":
        return type_text(expr.get("Child") or {}) + "[]"
    if kind == "Array":
        count = (expr.get("Shape") or {}).get("Size", "?")
        return f"{type_text(expr.get('Child') or {})}[{count}]"
    if kind == "MissingClrType":
        return "missing-type*"
    return str(kind or "?")


class CalmProjectionWriter:
    def __init__(self, model: Win32JsonModel, out_dir: Path):
        if model.arch != "x64":
            raise SystemExit("the CALM projection currently implements the Win64 contract surface only")
        self.model = model
        self.out_dir = out_dir
        self.dll_aliases = model.dll_aliases()
        self.type_names = {decl.name for decl in model.types if decl.parent is None}
        self.contracts = self._build_contracts()

    def _build_contracts(self) -> list[FunctionContract]:
        used_ids: set[str] = set()
        contracts: list[FunctionContract] = []
        for index, item in enumerate(self.model.functions):
            set_name = "apisets" if is_apiset_dll(item["DllImport"]) else "downlevel"
            dll_alias = self.dll_aliases[item["DllImport"]]
            contract_name = safe_component(item["Name"])
            stem = safe_component(f"fn__{dll_alias}__{item['Name']}")
            target_id = stem
            suffix = 2
            while target_id in used_ids:
                target_id = f"{stem}__{suffix}"
                suffix += 1
            used_ids.add(target_id)
            canonical = f"win32.api.{dll_alias}.{contract_name}"
            contracts.append(
                FunctionContract(
                    index=index,
                    item=item,
                    set_name=set_name,
                    dll_alias=dll_alias,
                    source_name=item["Name"],
                    contract_name=contract_name,
                    target_id=target_id,
                    canonical=canonical,
                )
            )

        for set_name in ("downlevel", "apisets"):
            members = [contract for contract in contracts if contract.set_name == set_name]
            by_name: dict[str, list[FunctionContract]] = defaultdict(list)
            for contract in members:
                by_name[contract.source_name].append(contract)
            for name, group in by_name.items():
                if len(group) > 1:
                    for contract in group:
                        contract.public_reason = "duplicate function name in selected set"
                    continue
                contract = group[0]
                if contract.contract_name != name:
                    contract.public_reason = "name requires sanitizing or is reserved"
                elif is_rename(name) or name.lower() in RUNTIME_NAMES:
                    contract.public_reason = "reserved projection/fasmg name"
                elif name in self.type_names:
                    contract.public_reason = "collides with a Win32 type/interface name"
                else:
                    contract.public = True
        return contracts

    def write(self, clean: bool = False) -> None:
        if clean and self.out_dir.exists():
            resolved = self.out_dir.resolve()
            if resolved.name not in {"x64", "x86", "arm64"}:
                raise SystemExit(f"refusing to clean unexpected output directory: {resolved}")
            shutil.rmtree(resolved)
        self.out_dir.mkdir(parents=True, exist_ok=True)
        self._write_runtime()
        self._write_values()
        self._write_types()
        for set_name in ("downlevel", "apisets"):
            self._write_contract_set(set_name)
            self._write_backend_set(set_name)
        self._write_top_level()
        self._write_meta()

    def _write_text(self, relative: str, lines: list[str] | str) -> None:
        path = self.out_dir / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        text = lines if isinstance(lines, str) else "\n".join(lines) + "\n"
        path.write_text(text, encoding="utf-8", newline="\n")

    def _header(self, title: str) -> list[str]:
        return [GENERATED_MARKER, f"; {title}", ""]

    def _write_runtime(self) -> None:
        adapter = """; Generated runtime protocol adapter.
; The final Win64 scheduler may replace this implementation while retaining
; the win32.fastcall target-and-operand-list interface.

namespace win32

        define linkage

        calminstruction fastcall target*,&arguments&
                local line,slot

                match {slot},target
                jyes lower
                transform target,linkage

        lower:
                match ,arguments
                jyes no_arguments
                arrange line,=fastcall target,arguments
                assemble line
                exit

        no_arguments:
                arrange line,=fastcall target
                assemble line
        end calminstruction

end namespace
"""
        self._write_text("runtime/fastcall_adapter.g", adapter)

        import64 = """; Projection-owned used-only PE64 import materializer.

macro win32.library? definitions&
        PE.Imports:
        iterate <name,string>, definitions
                if ~ name.redundant
                        dd RVA name.lookup,0,0,RVA name.str,RVA name.address
                end if
                name.referred = 1
        end iterate
        dd 0,0,0,0,0
        iterate <name,string>, definitions
                if ~ name.redundant
                        name.str db string,0
                        align 2
                end if
        end iterate
end macro

macro win32.import? name,definitions&
        align 8
        if defined name.referred
                name.lookup:
                iterate <label,string>, definitions
                        if used label
                                dq RVA name.label
                        end if
                end iterate
                if $ > name.lookup
                        name.redundant = 0
                        dq 0
                else
                        name.redundant = 1
                end if
                name.address:
                iterate <label,string>, definitions
                        if used label
                                label dq RVA name.label
                        end if
                end iterate
                if ~ name.redundant
                        dq 0
                end if
                iterate <label,string>, definitions
                        if used label
                                name.label dw 0
                                db string,0
                                align 2
                        end if
                end iterate
        end if
end macro
"""
        self._write_text("runtime/import64.g", import64)

    def _write_values(self) -> None:
        enum_lines = self._header("Typed enum and Boolean namespaces")
        enum_lines.extend(
            [
                "define win32 win32",
                "define win32.BOOL win32.BOOL",
                "define win32.BOOL.FALSE 0",
                "define win32.BOOL.TRUE 1",
                "define win32.BOOLEAN win32.BOOLEAN",
                "define win32.BOOLEAN.FALSE 0",
                "define win32.BOOLEAN.TRUE 1",
                "",
            ]
        )
        for decl in sorted((d for d in self.model.types if d.kind == "Enum"), key=lambda d: d.emitted.lower()):
            flat = safe_component(decl.emitted)
            enum_lines.append(f"; {decl.api}.{decl.name}")
            enum_lines.append(f"define win32.{flat} win32.{flat}")
            for value in decl.item.get("Values", []) or []:
                name = safe_component(value["Name"])
                rendered = fasm_value(value["Value"])
                enum_lines.append(f"define win32.{flat}.{name} {rendered}")
            enum_lines.append("")
        self._write_text("values/enums.g", enum_lines)

        constant_lines = self._header("Vertically namespaced constants")
        for index, item in enumerate(self.model.constants):
            api = safe_component(api_prefix(item["_api"]))
            name = safe_component(item["Name"])
            value = item.get("Value")
            if value is None and item.get("ValueType") == "String":
                value = ""
            try:
                rendered = fasm_value(value)
            except ValueError:
                continue
            constant_lines.append(f"define win32.constant.{api}.{name} {rendered}")
        self._write_text("values/constants.g", constant_lines)
        self._write_text(
            "values.g",
            self._header("Unified value surface")
            + ["include 'values/enums.g'", "include 'values/constants.g'"],
        )

    def _write_types(self) -> None:
        renderer = Fasm2Writer(self.model, self.out_dir)
        selected = [("Networking.WinSock", "WSAData")]
        includes: list[str] = []
        for api, name in selected:
            decl = self.model.top_type_by_api_name[(api, name)]
            api_path = safe_component(api).lower()
            relative = f"types/{api_path}/{safe_component(decl.emitted)}.g"
            record_lines = [line[1:] if line.startswith("?") else line for line in renderer.render_record(decl)]
            self._write_text(
                relative,
                self._header(f"Selective x64 type: {api}.{name}")
                + record_lines,
            )
            includes.append(relative)

        self._write_text(
            "types.g",
            self._header("Selective x64 type surface")
            + [
                "; Include only the layouts a consumer needs. Available slices:",
                *[f";   include '{path}'" for path in includes],
            ],
        )

    def _parameter_names(self, item: dict[str, Any]) -> list[str]:
        used: set[str] = set()
        names: list[str] = []
        for index, param in enumerate(item.get("Params", []) or [], 1):
            raw = param.get("Name") or f"arg{index}"
            base = safe_component(raw)
            if base in {"target", "arguments", "line", "slot"}:
                base += "_"
            name = base
            suffix = 2
            while name in used:
                name = f"{base}_{suffix}"
                suffix += 1
            used.add(name)
            names.append(name)
        return names

    def _resolver_for(
        self,
        item: dict[str, Any],
        param: dict[str, Any],
    ) -> str | None:
        semantic = SEMANTIC_PARAM_RESOLVERS.get(
            (item["DllImport"], item["Name"], param.get("Name") or "")
        )
        if semantic:
            return semantic
        expr = param.get("Type") or {}
        if expr.get("Kind") != "ApiRef":
            return None
        name = expr.get("Name")
        if name in ("BOOL", "BOOLEAN"):
            return f"win32.{name}"
        decl = self.model.resolve_apiref(expr, None)
        if decl and decl.kind == "Enum":
            return f"win32.{safe_component(decl.emitted)}"
        return None

    def _render_header(self, name: str, formals: list[str]) -> list[str]:
        if not formals:
            return [f"calminstruction {name}"]
        lines = [f"calminstruction {name} \\"]
        for offset in range(0, len(formals), 3):
            chunk = formals[offset : offset + 3]
            suffix = ",\\" if offset + 3 < len(formals) else ""
            lines.append("\t" + ",".join(chunk) + suffix)
        return lines

    def _render_contract(self, contract: FunctionContract, public_name: str | None = None) -> list[str]:
        item = contract.item
        name = public_name or contract.canonical
        params = item.get("Params", []) or []
        param_names = self._parameter_names(item)
        formals = []
        for param, param_name in zip(params, param_names):
            optional = "Optional" in (param.get("Attrs") or [])
            formals.append(f"{param_name}:0" if optional else f"{param_name}*")

        lines = [
            f"; {item['_api']}.{item['Name']} from {item['DllImport']}",
            f"; return: {type_text(item.get('ReturnType') or {})}; SetLastError={str(bool(item.get('SetLastError'))).lower()}",
        ]
        for param in params:
            attrs = ",".join(
                attr if isinstance(attr, str) else json.dumps(attr, sort_keys=True, separators=(",", ":"))
                for attr in (param.get("Attrs") or [])
            ) or "-"
            lines.append(f";   {param.get('Name')}: {type_text(param.get('Type') or {})} [{attrs}]")
        lines.extend(self._render_header(name, formals))
        lines.append("\tlocal target,arguments")
        lines.append(f"\tinitsym target,{contract.target_id}")
        for param, param_name in zip(params, param_names):
            resolver = self._resolver_for(item, param)
            if resolver:
                lines.append(f"\ttransform {param_name},{resolver}")
        if param_names:
            lines.append("\tarrange arguments," + ",".join(param_names))
            lines.append("\tcall win32.fastcall,target,arguments")
        else:
            lines.append("\tcall win32.fastcall,target")
        lines.append("end calminstruction")
        lines.append("")
        return lines

    def _render_alias(self, contract: FunctionContract, public_name: str) -> list[str]:
        params = contract.item.get("Params", []) or []
        param_names = self._parameter_names(contract.item)
        formals = []
        for param, param_name in zip(params, param_names):
            optional = "Optional" in (param.get("Attrs") or [])
            formals.append(f"{param_name}:0" if optional else f"{param_name}*")
        lines = [
            f"; {public_name} -> {contract.canonical}",
            *self._render_header(public_name, formals),
        ]
        if param_names:
            lines.append(f"\tcall {contract.canonical}," + ",".join(param_names))
        else:
            lines.append(f"\tcall {contract.canonical}")
        lines.extend(["end calminstruction", ""])
        return lines

    def _write_contract_set(self, set_name: str) -> None:
        members = [contract for contract in self.contracts if contract.set_name == set_name]
        by_dll: dict[str, list[FunctionContract]] = defaultdict(list)
        for contract in members:
            by_dll[contract.dll_alias].append(contract)

        qualified_index = self._header(f"Qualified {set_name} function contracts")
        public_index = self._header(f"Collision-safe public {set_name} function contracts")
        for dll_alias in sorted(by_dll):
            contracts = sorted(by_dll[dll_alias], key=lambda c: (c.source_name.lower(), c.index))
            qualified_path = f"contracts/{set_name}/qualified/{dll_alias}.g"
            public_path = f"contracts/{set_name}/public/{dll_alias}.g"
            qualified_lines = self._header(f"Qualified contracts for {contracts[0].item['DllImport']}")
            public_lines = self._header(f"Public aliases for {contracts[0].item['DllImport']}")
            for contract in contracts:
                qualified_lines.extend(self._render_contract(contract))
                if contract.public:
                    public_lines.extend(self._render_alias(contract, contract.source_name))
            self._write_text(qualified_path, qualified_lines)
            self._write_text(public_path, public_lines)
            qualified_index.append(f"include '{qualified_path}'")
            public_index.append(f"include '{public_path}'")

        self._write_text(f"contracts/{set_name}/qualified.g", qualified_index)
        public_gate = self._header(f"Public {set_name} selection gate") + [
            "if definite WIN32JSON_CALM_PUBLIC_FUNCTION_SET",
            "\terr 'a public Win32 function subset is already selected'",
            "else",
            f"WIN32JSON_CALM_PUBLIC_FUNCTION_SET = {1 if set_name == 'downlevel' else 2}",
            "end if",
            "",
            *public_index[3:],
        ]
        self._write_text(f"contracts/{set_name}/public.g", public_gate)
        self._write_text(
            f"contracts/{set_name}.g",
            self._header(f"Unified {set_name} contract subset")
            + [
                f"include 'contracts/{set_name}/qualified.g'",
                f"include 'contracts/{set_name}/public.g'",
            ],
        )

        duplicates: dict[str, list[FunctionContract]] = defaultdict(list)
        for contract in members:
            if contract.public_reason == "duplicate function name in selected set":
                duplicates[contract.source_name].append(contract)
        collision_index = self._header(f"Explicit {set_name} function collision selectors")
        for name in sorted(duplicates):
            for contract in duplicates[name]:
                selector = safe_component(f"{name}.{contract.dll_alias}")
                relative = f"contracts/{set_name}/collisions/{selector}.g"
                lines = self._header(
                    f"Explicit raw-name selector: {name} -> {contract.item['DllImport']}"
                )
                lines.append(
                    f"include 'contracts/{set_name}/qualified/{contract.dll_alias}.g'"
                )
                lines.extend(self._render_alias(contract, name))
                self._write_text(relative, lines)
                collision_index.append(f"; include '{relative}'")
        self._write_text(f"contracts/{set_name}/collisions.g", collision_index)

    def _write_backend_set(self, set_name: str) -> None:
        members = [contract for contract in self.contracts if contract.set_name == set_name]
        by_dll: dict[str, list[FunctionContract]] = defaultdict(list)
        for contract in members:
            by_dll[contract.dll_alias].append(contract)

        indexes = {
            backend: self._header(f"{backend} linkage for {set_name} contracts")
            for backend in ("recording", "coff", "pe")
        }
        for dll_alias in sorted(by_dll):
            contracts = sorted(by_dll[dll_alias], key=lambda c: (c.source_name.lower(), c.index))
            recording = self._header(f"Recording linkage for {contracts[0].item['DllImport']}")
            coff = self._header(f"Microsoft COFF linkage for {contracts[0].item['DllImport']}")
            pe = self._header(f"Direct PE linkage for {contracts[0].item['DllImport']}")
            seen_externals: set[str] = set()
            for contract in contracts:
                recording.append(f"define win32.linkage.{contract.target_id} {contract.index + 1}")
                coff.append(f"define win32.linkage.{contract.target_id} {contract.source_name}")
                seen_externals.add(contract.source_name)
                iat = safe_component(f"win32_iat__{contract.target_id}")
                pe.append(f"define win32.linkage.{contract.target_id} [{iat}]")
            coff.extend(["", "postpone"])
            for external in sorted(seen_externals, key=str.lower):
                coff.extend(
                    [
                        f"\tif used {external}",
                        f"\t\textrn {external}",
                        "\tend if",
                    ]
                )
            coff.append("end postpone")
            for backend, lines in (("recording", recording), ("coff", coff), ("pe", pe)):
                relative = f"backends/{backend}/{set_name}/{dll_alias}.g"
                self._write_text(relative, lines)
                indexes[backend].append(f"include '{relative}'")

        for backend, lines in indexes.items():
            self._write_text(f"backends/{backend}/{set_name}.g", lines)

        import_lines = self._header(f"Used-only PE64 imports for {set_name}")
        import_lines.append("include 'runtime/import64.g'")
        import_lines.append("win32.library \\")
        dlls = sorted(by_dll)
        for index, dll_alias in enumerate(dlls):
            dll = by_dll[dll_alias][0].item["DllImport"]
            suffix = ",\\" if index + 1 < len(dlls) else ""
            import_lines.append(
                f"\twin32_dll__{dll_alias},{fasm_string(dll)}{suffix}"
            )
        import_lines.append("")
        for dll_alias in dlls:
            contracts = sorted(by_dll[dll_alias], key=lambda c: (c.source_name.lower(), c.index))
            import_lines.append(f"win32.import win32_dll__{dll_alias},\\")
            for index, contract in enumerate(contracts):
                suffix = ",\\" if index + 1 < len(contracts) else ""
                iat = safe_component(f"win32_iat__{contract.target_id}")
                import_lines.append(f"\t{iat},{fasm_string(contract.source_name)}{suffix}")
            import_lines.append("")
        self._write_text(f"backends/pe/{set_name}_imports.g", import_lines)

    def _write_top_level(self) -> None:
        self._write_text(
            "windows.g",
            self._header("Unified common Win32 projection")
            + ["include 'runtime/fastcall_adapter.g'", "include 'values.g'"],
        )
        windows_inc = r"""; Generated by scripts/win32json_fasm2_calm.py. DO NOT EDIT.
; Format-aware selective Win32 projection

include 'windows.g'

macro _win32_include_library? set*,library*
        local path
        if definite PE.Settings.Machine
                if PE.Settings.Machine <> IMAGE_FILE_MACHINE_AMD64
                        err 'x64 windows.inc requires an AMD64 PE format'
                end if
                define path 'backends/pe/' bappend `set bappend '/' bappend `library bappend '.g'
        else if definite COFF.Settings.Machine
                if COFF.Settings.Machine <> IMAGE_FILE_MACHINE_AMD64
                        err 'x64 windows.inc requires an AMD64 Microsoft COFF format'
                end if
                define path 'backends/coff/' bappend `set bappend '/' bappend `library bappend '.g'
        else if definite NEWCOFF.RELOC_REL32
                if x86.mode <> 64
                        err 'x64 windows.inc requires 64-bit NEWCOFF mode'
                end if
                define path 'backends/coff/' bappend `set bappend '/' bappend `library bappend '.g'
        else
                err 'windows.inc requires PE or Microsoft COFF format selection first'
        end if
        include path
        define path 'contracts/' bappend `set bappend '/qualified/' bappend `library bappend '.g'
        include path
        define path 'contracts/' bappend `set bappend '/public/' bappend `library bappend '.g'
        include path
end macro

win32.selected.downlevel = 0
win32.selected.apisets = 0

match =win32.select.downlevel,win32.select.downlevel
else
        win32.selected.downlevel = 1
        match libraries,win32.select.downlevel
                iterate library,libraries
                        _win32_include_library downlevel,library
                end iterate
        end match
end match

match =win32.select.apisets,win32.select.apisets
else
        win32.selected.apisets = 1
        match libraries,win32.select.apisets
                iterate library,libraries
                        _win32_include_library apisets,library
                end iterate
        end match
end match

purge _win32_include_library

postpone
        if definite PE.Settings.Machine
                if win32.selected.downlevel & win32.selected.apisets
                        err 'combined down-level/API-set PE import materialization is not implemented'
                end if
                section '.idata' import data readable writeable
                if win32.selected.downlevel
                        include 'backends/pe/downlevel_imports.g'
                else if win32.selected.apisets
                        include 'backends/pe/apisets_imports.g'
                end if
        end if
end postpone
"""
        self._write_text("windows.inc", windows_inc)
        self._write_text(
            "windows_downlevel.g",
            self._header("Unified concrete/down-level function projection")
            + ["include 'windows.g'", "include 'contracts/downlevel.g'"],
        )
        self._write_text(
            "windows_apisets.g",
            self._header("Unified API-set function projection")
            + ["include 'windows.g'", "include 'contracts/apisets.g'"],
        )
        self._write_text(
            "windows_qualified.g",
            self._header("Both function sets, qualified names only")
            + [
                "include 'windows.g'",
                "include 'contracts/downlevel/qualified.g'",
                "include 'contracts/apisets/qualified.g'",
            ],
        )

    def _write_meta(self) -> None:
        rows = [
            "set\tdll\tapi\tfunction\tcanonical\ttarget_id\tparams\tpublic\treason"
        ]
        collision_rows = ["set\tfunction\tdll\tcanonical\treason"]
        for contract in self.contracts:
            reason = contract.public_reason
            rows.append(
                "\t".join(
                    [
                        contract.set_name,
                        contract.item["DllImport"],
                        contract.item["_api"],
                        contract.source_name,
                        contract.canonical,
                        contract.target_id,
                        str(len(contract.item.get("Params", []) or [])),
                        "yes" if contract.public else "no",
                        reason,
                    ]
                )
            )
            if reason:
                collision_rows.append(
                    "\t".join(
                        [
                            contract.set_name,
                            contract.source_name,
                            contract.item["DllImport"],
                            contract.canonical,
                            reason,
                        ]
                    )
                )
        self._write_text("meta/functions.tsv", rows)
        self._write_text("meta/function_collisions.tsv", collision_rows)
        summary = {
            "arch": self.model.arch,
            "functions": len(self.contracts),
            "downlevel_functions": sum(c.set_name == "downlevel" for c in self.contracts),
            "apiset_functions": sum(c.set_name == "apisets" for c in self.contracts),
            "public_downlevel": sum(c.set_name == "downlevel" and c.public for c in self.contracts),
            "public_apisets": sum(c.set_name == "apisets" and c.public for c in self.contracts),
            "withheld_public_aliases": sum(not c.public for c in self.contracts),
            "duplicate_function_names": sorted(
                {
                    c.source_name
                    for c in self.contracts
                    if c.public_reason == "duplicate function name in selected set"
                }
            ),
        }
        self._write_text("meta/summary.json", json.dumps(summary, indent=2, sort_keys=True) + "\n")


def build_model(api_dir: str, arch: str) -> Win32JsonModel:
    path = Path(api_dir).resolve()
    if not path.exists():
        raise SystemExit(f"api directory not found: {path}")
    model = Win32JsonModel(path, arch)
    model.load()
    return model


def verify(out_dir: Path, model: Win32JsonModel) -> int:
    required = [
        "windows.g",
        "windows_downlevel.g",
        "windows_apisets.g",
        "windows_qualified.g",
        "values.g",
        "contracts/downlevel.g",
        "contracts/apisets.g",
        "backends/coff/downlevel.g",
        "backends/coff/apisets.g",
        "backends/pe/downlevel.g",
        "backends/pe/apisets.g",
        "backends/pe/downlevel_imports.g",
        "backends/pe/apisets_imports.g",
        "meta/functions.tsv",
        "meta/function_collisions.tsv",
        "meta/summary.json",
    ]
    errors = [f"missing {name}" for name in required if not (out_dir / name).exists()]
    if not errors:
        summary = json.loads((out_dir / "meta/summary.json").read_text(encoding="utf-8"))
        if summary.get("functions") != len(model.functions):
            errors.append("generated function count does not match model")
        if summary.get("downlevel_functions", 0) + summary.get("apiset_functions", 0) != len(model.functions):
            errors.append("function subset counts do not add up")
        duplicate_counts: Counter[tuple[str, str]] = Counter()
        for item in model.functions:
            set_name = "apisets" if is_apiset_dll(item["DllImport"]) else "downlevel"
            duplicate_counts[(set_name, item["Name"])] += 1
        expected_duplicates = sorted(
            name for (_set_name, name), count in duplicate_counts.items() if count > 1
        )
        if summary.get("duplicate_function_names") != expected_duplicates:
            errors.append(
                f"unexpected duplicate function-name set: {summary.get('duplicate_function_names')}"
            )
    if errors:
        for error in errors:
            print(f"verify: {error}")
        return 1
    print(f"verify: unified CALM projection ok ({model.arch}, {out_dir})")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    for command in ("generate", "verify"):
        p = sub.add_parser(command)
        p.add_argument("--api-dir", default="api")
        p.add_argument("--arch", choices=("x64",), default="x64")
        p.add_argument("--out-dir", default="generated/fasm2_calm/x64")
        if command == "generate":
            p.add_argument("--clean", action="store_true")
    args = parser.parse_args(argv)
    model = build_model(args.api_dir, args.arch)
    out_dir = Path(args.out_dir).resolve()
    if args.command == "generate":
        CalmProjectionWriter(model, out_dir).write(clean=args.clean)
        print(f"generated unified CALM projection at {out_dir}")
    return verify(out_dir, model)


if __name__ == "__main__":
    raise SystemExit(main())
